baseURL = "https://squaresurf.github.io/"
languageCode = "en-us"
theme = "squaresurf"
title = "SquareSurf"

[Params]
  author = "Daniel Paul Searles"
  description = "A blog for github user squaresurf with topics mostly ranging from Data Science to Functional Programming."
  pygmentsUseClasses = true
